---
- name: shutdown all nodes
  hosts: all:!DEBIAN_TEMPLATE:!VYOS
  become: yes

  tasks:
  - name: shutdown server
    command: "shutdown now"
    async: 1
    poll: 0

- name: shutdown all nodes
  hosts: VYOS
  become: yes

  tasks:
  - name: shutdown router
    command: "shutdown 1"
    async: 1
    poll: 0

