---
- name: br_netfilter check
  hosts: K8S01
  become: yes

  tasks:
  - name: remove config.toml
    file:
      path: /etc/containerd/config.toml
      state: absent
    register: result

  - name: restart containerd
    systemd:
      name: containerd
      state: restarted
    when: result is changed

