---
# tasks file for roles/Add-DockerInsecureRegistry
- name: make directory
  ansible.builtin.file:
    path: /etc/docker
    state: directory
    mode: '0755'

- name: copy files
  ansible.builtin.copy:
    src: daemon.json
    dest: /etc/docker/daemon.json

- name: restart docker service
  ansible.builtin.service:
    name: docker.service
    state: restarted

