---
# tasks file for roles/Change-MachineId
- name: remove /etc/machine-id
  ansible.builtin.file:
    path: /etc/machine-id
    state: absent

- name: remove /var/lib/dbus/machine-id
  ansible.builtin.file:
    path: /var/lib/dbus/machine-id
    state: absent

- name: generate new machine-id
  command: systemd-machine-id-setup

