---
# tasks file for roles/Install-Docker
#- name: install curl
#  ansible.builtin.apt:
#    name: curl
#    state: present

- name: save sh script
  get_url:
    url: "{{ docker_install_url }}"
    dest: "{{ temp_script_name }}"

- name: install docker
  shell: "sh {{ temp_script_name }}"
  args:
    executable: "/bin/sh"

- name: delete sh script
  file:
    path: "{{ temp_script_name }}"
    state: absent

